name: Feature pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode version # Xcode 12.4 を使う
      run: sudo xcode-select -s '/Applications/Xcode_12.4.app/Contents/Developer'
    - name: Build
      run: xcodebuild
            -scheme Sample
            -sdk iphonesimulator
            -configuration Debug
            build
      # Run unit test
    - name: Run tests
      run: xcodebuild
            -scheme SampleTest
            -sdk iphonesimulator
            -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
            -resultBundlePath ./
            clean test
