name: Feature pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#  build:
#    runs-on: macos-latest
#    name: Build
#    steps:
#    - uses: actions/checkout@v2
#    - name: Select Xcode version # Xcode 12.4 を使う
#      run: sudo xcode-select -s '/Applications/Xcode_12.4.app/Contents/Developer'
#    - name: Build
#      run: xcodebuild
#            -scheme Sample
#            -sdk iphonesimulator
#            -configuration Debug
#            build
      # Run unit test
  
  unit_test:
    runs-on: macos-10
    name: Unit test
    steps:
    - uses: actions/checkout@v2
    
    - name: Show Xcode list
      run: ls /Applications | grep 'Xcode'
    
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_12.5.1.app/Contents/Developer'
    
    - name: Simulator Lists
      run: xcrun simctl list
    
    - name: Check Available destination
      run: xcodebuild build -scheme Sample -showdestinations
    
    - name: Unite Tests
      run: set -o pipefail && xcodebuild
            -scheme Sample
            -sdk iphonesimulator
            -destination "platform=iOS Simulator,OS=14.4,name=iPhone 11 Pro Max"
            -resultBundlePath TestResultsB
            -skip-testing SampleUITests
            clean test | xcpretty
